### ISSUE TITLE
[BUG] Assemble task requires integTest configuration

### ISSUE THREAD

**Issue by dblock** [opensearch-project/index-management#122]
**Describe the bug**

**To Reproduce**

```
rm src/test/resources/job-scheduler/opensearch-job-scheduler-1.0.0.0.zip
./gradlew assemble

> Configure project :
mixed cluster flag: false

FAILURE: Build failed with an exception.

* Where:
Build file '/home/ubuntu/source/opensearch-project/index-management/dblock-index-management/build.gradle' line: 361

* What went wrong:
A problem occurred evaluating root project 'opensearch-index-management'.
> Expected directory 'src/test/resources/job-scheduler' to contain exactly one file, however, it contains no files.
```

**Expected behavior**

The .zip is required by `integTest`, so this part shouldn't evaluate unless I want to run integ tests.

**Comment by bowenlan-amzn** [comment]
Not a gradle expert, but I think this is because gradle will evaluate all tasks defined inside `build.gradle` before running any task.
If I delete the file inside `src/test/resources/job-scheduler`, and run `./gradlew clean`, it will also fail. Task `clean` doesn't even depends on anything.
So this doesn't seem to be a bug to me.
