### ISSUE TITLE
Enable additional parameters in the snapshot function

### ISSUE THREAD

**Issue by gunnar170566** [opensearch-project/index-management#127]
Today, the ISM operation "snapshot" takes two parameters:
```
{
  "snapshot": {
    "repository": "my_backup",
    "snapshot": "my_snapshot"
  }
}
```
The API - Snapshot function takes three additional parameters:
```
PUT _snapshot/my-repository/2
{
  "indices": "kibana*,my-index*,-my-index-2016",
  "ignore_unavailable": true,
  "include_global_state": false,
  "partial": false
}
```
It would be usefull to enable the full set of parameters in the ISM operation "snapshot", i.e. adding:
- ignore_unavailable
- include_global_state
- partial

**Comment by dbbaughe** [comment]
Hmm I think we had intentionally ignored include global state because it would have previously not played nice with the plugin when we were storing the state of the managed indices (metadata) in the cluster state.

Since we have removed the metadata from the cluster state and into the config index... seems like that shouldn't be an issue anymore. Don't see a reason why we can't add support for these.

@thalurur Any risk you see?

**Comment by bowenlan-amzn** [comment]
Snapshot management support these parameters, please check it out. https://opensearch.org/docs/latest/opensearch/snapshots/sm-api#create-or-update-a-policy

**Comment by gunnar170566** [comment]
Thank you very much, we will start testing asap.

Best regards - Gunnar
