### ISSUE TITLE
[BUG] Failed to clear ManagedIndexMetadata for index uuid  IndexNotFoundException[no such index [.opendistro-ism-config]]

### ISSUE THREAD

**Issue by meghasaik** [opensearch-project/index-management#167]
**Describe the bug**
Getting a `Failed to clear ManagedIndexMetadata for index uuid: [OnFSdsEUQZS_ti17nKtQCA#metadata], failureMessage: [.opendistro-ism-config] IndexNotFoundException[no such index [.opendistro-ism-config]]` when trying to update the ansible script from ELK 7.10.2 to opensearch-1.0.0-rc1. This error occurred while trying to solve another bug: https://github.com/opensearch-project/opensearch/issues/845 related to AccessDenied Opensearch-Dashboards error.

**To Reproduce**
-The steps are given in the issue as well as in the comments of the Issue:  
https://github.com/opensearch-project/opensearch/issues/845
https://github.com/opensearch-project/opensearch/issues/845#issuecomment-937018028

**Expected behavior**
Expected to get the AccessDenied: Opensearch-Dashboards error but this error did not occur and the Dashboards was running. Instead got the bug mentioned above.

**Screenshots**

<img width="1488" alt="Screen Shot 2021-10-04 at 4 21 08 PM" src="https://user-images.githubusercontent.com/44311835/136272870-afd102a0-93fd-4765-a3a2-a7fe57378476.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu (EC2 instance)
 - Version: 20.04

**Comment by bowenlan-amzn** [comment]
Hi, this is a known issue. [Refer](https://github.com/opensearch-project/index-management/blame/11883ae9f81c9cfbbc3f45c0c71951bf1f223206/src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/ManagedIndexCoordinator.kt#L665)
It's fixed in version 1.0+ but we recommend upgrading to 1.1. 
1.0 and 1.0.1 has some know ISM plugin issues we fixed in 1.1.
