### ISSUE TITLE
[BUG] Rollup action inside index policy not executed in the second day for a daily deleted and created index

### ISSUE THREAD

**Issue by louzadod** [opensearch-project/index-management#372]
**What is the bug?**
When an index is deleted and created every day, the policy gets applied properly and the states in the policy get transitioned OK.
But, in the last state I have a rollup action. 
When I create the policy and apply to the index for the first time, the policy runs properly and the rollup action gets done.
Then, the rollup action changes to "disabled".
In the second day, after index deletion and creation, the policy executes OK but the rollup action does not because the rollup job kept "disabled".

I think that the policy should re-enable the rollup job again. When I go to Index Management, Rollup jobs, and re-enable the job, the rollup runs OK. But I have to do it daily.

**How can one reproduce the bug?**
1. Create a test index with some data
2. Create index policy with rollup action
3. Apply policy to index
4. In the next moment, delete, recreate and repopulate the test index
5. Watch policy being re-applied again to the index by calling `GET _plugins/_ism/explain/test-index`
6. Wait for rollup action and confirm it did not run as expected by calling `GET _plugins/_rollup/jobs/your-rollup-job-id/_explain`

**What is the expected behavior?**
In the second day the policy will re-enable and re-invoke the rollup job properly

**What is your host/environment?**
 - Linux amd64 / Kubernetes v1.20.9 / Rancher 2.5.7
 - OpenSearch 1.3.2 official docker image
 - Official set of plugins (no customization)

**Comment by louzadod** [comment]
I'm considering the following workaround: delete rollup job (if exists) and create it every day out of ISM policy.
What do you think about this?

**Comment by bowenlan-amzn** [comment]
> I'm considering the following workaround: delete rollup job (if exists) and create it every day out of ISM policy. What do you think about this?

Hi @louzadod, I looked into this issue. The root cause is ISM rollup action use the hash of the managed index name to be the rollup job id. So if the index name is same, rollup job cannot be created in the second time.

You proposed solution makes sense and I don't see any downside of it. 2 ways forward:
- you have some periodic job to clean that rollup job (need to get back all rollup jobs and find the one with the right source index and delete it)
- we can add a new option in ISM rollup job to force delete the rollup jobs if exists. Lemme know if you want to help on this feature enhancement.

Also, I am curious the way you uses rollup. Rollup is mainly for time series indices, instead of delete index and create everyday, we normally expect user to have it rollover every day so index names would be different and won't have this problem. Would you mind share more on your use case?

**Comment by bowenlan-amzn** [comment]
Feel free to re-open this.

**Comment by louzadod** [comment]
Hi @bowenlan-amzn.

My use case is pretty different from typical log ingestion. I generate a vulnerability report every day and store it on a clean (delete and recreate) index. Then, I roll it up to a historical index (much smaller) in order to have statistical information. The goal is to retain this information for years.
