### ISSUE TITLE
[BUG] Restoring Indices Loses ISM Policy Associations

### ISSUE THREAD

**Issue by lobsterdore** [opensearch-project/index-management#376]
**Describe the bug**
This is for OpenSearch as a service on AWS. I am working on tearing down the OS Domains overnight to save money.

The process (detailed in 'To Reproduce') restores pretty much everything apart from the ISM config for the restored indices, I cannot seem to restore any of the '.opensearch' indices as this results in a 403, so I am not sure how to bring back restored indices with their previous ISM policy assignment. Is this even possible?

**To Reproduce**

* Have an OpenSearch instance with some indices that have ISM policies attached
* Take a snapshot of all indices
* Destroy the OpenSearch instance
* Bring up a fresh OpenSearch instance and recreate the ISM policy
* Restore snapshot taken leaving out .opensearch indices as this seems to cause a 403

**Expected behavior**
I would expect to be able to restore indices with the same ISM policy assignment that they had previously.

**Host/Environment (please complete the following information):**
AWS OpenSearch 1.1

**Comment by bowenlan-amzn** [comment]
ISM configurations including policies, attachment, managed index metatadata are all saved in `.opendistro-ism-config`. So if you can restore this config index back, you can get back all these.

However ISM doesn't support continue managing the restored managed indices after you restore the config index. This is because the restored index has a new uuid, which is different from the uuid saved in restored managed index metadata, and ISM cannot continue managing when these 2 don't match. (This could be a feature request)

For the restored ISM policy, it doesn't have such issue.
