### ISSUE TITLE
[BUG] [Rollup]The doc_count results for the target index (after rollup) are incorrect

### ISSUE THREAD

**Issue by Shams-yang** [opensearch-project/index-management#378]
The doc_count results for the target index (after rollup) are incorrect

Step1  Import sample data opensearch_kibana_sample_data_flights using opensearch dashbord

Step2 create a rollup job for opensearch_kibana_sample_data_flights and target index is flights
timestamp filed : timestamp
Time aggregation : 1 day
DestCityName for terms  aggregation 
Step3:
The doc_count of Zurich is 691 in the source index and 43 in the target index
```
GET opensearch_kibana_sample_data_flights /_search
{
  "size": 0,
  "aggregations": {
    "DestCityName": {
      "terms": {
        "field": "DestCityName"
      }
    }
  }
}

"aggregations" : {
    "DestCityName" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 8610,
      "buckets" : [
        {
          "key" : "Zurich",
          "doc_count" : 691
        },
        {
          "key" : "Xi'an",
          "doc_count" : 526
        }
...
}
}
        

GET flights/_search
{
  "size": 0,
  "aggregations": {
    "DestCityName": {
      "terms": {
        "field": "DestCityName"
      }
    }
  }
}

"aggregations" : {
    "DestCityName" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 8610,
      "buckets" : [
        {
          "key" : "Zurich",
          "doc_count" : 43
        }
...
}
}
```

**Comment by downsrob** [comment]
During a rollup, the aggregations and metrics in the rollup policy are computed and indexed into the target rollup index such that when the rollup index is searched, the search may be intercepted and transformed to return the results as if the source index had been searched. In essence, we are bucketing the data ahead of time, which results in the doc_counts representing the count of buckets rather than the count of documents. 

This has been known, and is being tracked in the following enhancement issue https://github.com/opensearch-project/index-management/issues/57 please take a look and add any thoughts you have on the issue there! This is an important rollup enhancement which we are looking to resolve in the next few months.
