### ISSUE TITLE
[Best Practice] Permissions code with `allow access by default` patterns

### ISSUE THREAD

**Issue by peternied** [opensearch-project/index-management#473]
When checking for permissions, its possible that the user is set to null, when this occurs it has identical behavior as if the user was cluster admin.  This 'allow access by default' paradigm creates risk, no matter if it is an error in this code base, another plugin, or inside of OpenSearch; the result is a situation where unauthorized access/actions can occur.

Can we modify the code to deny access if the user is null?

https://github.com/opensearch-project/index-management/blob/279f7a6a148f2d31105c6fedbc5b72766b948bad/src/main/kotlin/org/opensearch/indexmanagement/util/SecurityUtils.kt#L137-L138

https://github.com/opensearch-project/index-management/blob/279f7a6a148f2d31105c6fedbc5b72766b948bad/src/main/kotlin/org/opensearch/indexmanagement/util/SecurityUtils.kt#L151-L152

See vulnerability classification [CWE-841: Improper Enforcement of Behavioral Workflow](https://cwe.mitre.org/data/definitions/841.html)

**Comment by bowenlan-amzn** [comment]
This is a backward compatibility consideration. 
For ISM user upgrade from older version that doesn't has security integration feature, the user object in the old ISM jobs is always null, and we don't want those to be blocked but to work with admin permission.

**Comment by peternied** [comment]
> For ISM user upgrade from older version

This seems like something that could be fixed with migration from previous versions to new versions that would no longer have this weakness

**Comment by bowenlan-amzn** [comment]
This is not really a weakness because our plugin security model is designed as this: 
1. If security integration feature is there, the user object is saved into system index which is supposed to be a safe place that cannot be manipulated. The only way to create/update the user object is by calling the ISM API, and ISM API will get the user information and save it behind the scene which also cannot be manipulated. 
2. user object can only be null if cluster is updated from an environment w/o ISM security integration feature. We treat this null user object as the admin.
