### ISSUE TITLE
[FEATURE] Support switch alias from source to target index in shrink action

### ISSUE THREAD

**Issue by bowenlan-amzn** [opensearch-project/index-management#676]
Support switch alias from source to target index in shrink action

**Comment by Jakob3xD** [comment]
Would be really nice to see this.
I currently have two polices that shrink indices before they get moved to cold nodes and loosing the read alias when shrink them is a real pain, as I now have to copy my polices for each index and use the `alias action` to apply the read alias again.

**Comment by ikibo** [comment]
@bowenlan-amzn could I be assigned to this issue plz? THNX!

**Comment by ikibo** [comment]
A point to take into account : 
When shrinking an index, there are two sources of aliases for the target-index:
- aliases from the shrink action in the policy
- aliases from the source index

Index alias is unique by name, and names of aliases may coincide in these two sources. In such a case, there is a collision, and priority will be given to the alias from the policy. Hence the target-index will possess an alias from the policy.

this is a natural decision, in such a way a client may override some properties of a source-index alias, and of course, add new aliases on demand.
if we follow this approach, we need to add this to the official [doc](https://opensearch.org/docs/latest/im-plugin/ism/policies/#shrink) for the correct release version, so that clients are aware, and are protected from undesired error/behaviour.

@bowenlan-amzn plz sign off if the above is good.

**Comment by bowenlan-amzn** [comment]
Yes, this idea looks good. 
Doc is needed for this, and would you please add a new param `switch_alias` in shrink action and default to false. Thanks!

**Comment by hdhalter** [comment]
@bowenlan-amzn - can you please add this to the roadmap/tracker for 2.12? Thanks!

**Comment by bowenlan-amzn** [comment]
@hdhalter added to the unified project tracker, pls lemme know if it's not right way
