### ISSUE TITLE
[BUG] ERROR log "get managed-index failed: [.opendistro-ism-config]"

### ISSUE THREAD

**Issue by olfuerniss** [opensearch-project/index-management#697]
**What is the bug?**
After index deletion an ERROR gets logged, even in a vanilla OpenSearch installation. Wondering what this means and why it gets logged as ERROR.

Happens with OpenSearch 2.4.0 and 2.5.0.

**How can one reproduce the bug?**

1. Download, extract and start
```
wget https://artifacts.opensearch.org/releases/bundle/opensearch/2.5.0/opensearch-2.5.0-linux-x64.tar.gz
tar xvfz opensearch-2.5.0-linux-x64.tar.gz
cd opensearch-2.5.0/
echo "plugins.security.disabled: true" >> config/opensearch.yml
bin/opensearch
```

2. Index a document / creates an index
```
curl -X PUT -H 'Content-Type: application/json' 'localhost:9200/students/_doc/1' --data-raw '{"name": "Isaac Newton", "age": 14, "performance": "honor student" }'
```

3. Delete the index
```
curl -X DELETE 'localhost:9200/students'
```

4. After index deletion you will find this ERROR in the logs.
```
[2023-02-22T13:14:30,159][ERROR][o.o.i.i.ManagedIndexCoordinator] [ofs-um690] get managed-index failed: [.opendistro-ism-config] IndexNotFoundException[no such index [.opendistro-ism-config]]
```

And you will see this ERROR log every time OpenSearch gets restarted.

**What is the expected behavior?**
Did not recognized any negative impact. It should not log them as ERROR or at least explain whats wrong.

**What is your host/environment?**
 - OS: Linux / Fedora
 - Version 37
 - Plugins: default

**Comment by ronnaksaxena** [comment]
@olfuerniss
Hi there!
Thanks for calling this out. This is actually intended behavior for the ISM plugin, and should not have any negative impact. However, we agree that logging this exception as an "ERROR" is inappropriate for this use case.
This occurs because the plugin listener picks up a "ClusterChangedEvent" whenever an index is deleted, as we want the plugin to then check for any plugin-specific metadata related to that index. However, since the ISM plugin had not been used yet in your example (e.g., an ISM policy hasn't been created), the .opendistro-ism-config index had not been created.
In [PR](https://github.com/opensearch-project/index-management/pull/846), I have added a WARN log instead of an ERROR that notifies the user no config index was found.
