### ISSUE TITLE
What are the current options to use cross-cluster replication and index state management together?

### ISSUE THREAD

**Issue by laszloszurok** [opensearch-project/index-management#714]
I use ISM policies to execute rollover operations on indices after their sizes reach a given limit. I also use CCR to replicate data between two clusters. In the ISM policies the "index_patterns" match both the leader indices and the follower indices. The problem is that after a leader index rolls over, its follower index can roll over on its own and then replication fails.

After a follower index incorrectly rolled over I see this in the OpenSearch logs (where follower-000001 is a replicated index, which rolled over to follower-000002):
`org.opensearch.ResourceNotFoundException: Metadata for follower-000002 doesn't exist`

Also:
`Cannot initiate replication for the following indices from leader (site-a) as indices with same name already exists on the cluster [follower1-000002, follower2-000002, ...]`

What is the correct way of using these plugins together? Is there a way to automatically delete the follower index after the leader got deleted?

OpenSearch version: 2.4.0

**Comment by Angie-Zhang** [comment]
Here are 2 solutions to avoid follower indices to be rolled over:
1. Use an index pattern in the rollover policy which does not match the follower indices. 
2. Skip rollover for follower indices by setting rollover_skip:
```
PUT /<index-name>/_settings
{
  "index.plugins.index_state_management.rollover_skip": true,
}
```

Is there a way to automatically delete the follower index after the leader got deleted?
ISM does not support this directly. However, we can consider these to solutions:
1. In Policy A, set an action to delete leader indices automatically, e.g. delete after 10 days; then in Policy B, set the same deletion rule for follower indices. We need two separated policies because we suggest using different patterns for leader indices and follower indices.
2. If you are going to delete indices by calling API, you can call DELETE for two indices at same time:
```
DELETE leader-index-1, follower-index-1
```
